apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: SSM
  annotations:
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key