apiVersion: v2
name: authentik
description: A Helm chart for Authentik
version: 0.1.0
dependencies:
  - name: authentik
    repository: https://charts.goauthentik.io
    version: 2025.4.1
  - name: postgresql
    version: 16.7.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: 21.1.6
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled