apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: default
  namespace: argo-cd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/bernardolsp/homelab.git
      revision: HEAD
      directories:
      - path: argo/*
  template:
    metadata:
      name: '{{index .path.segments 1}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/bernardolsp/homelab.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true