apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-external-secret
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 48h
  secretStoreRef:
    name: ssm
    kind: ClusterSecretStore
  target:
    name: authentik-external-secret
  data:
    - secretKey: postgres_user
      remoteRef:
        key: /homelab/prod/authentik_postgres_user
    - secretKey: postgres_password
      remoteRef:
        key: /homelab/prod/authentik_postgres_password