apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secret
  namespace: strrl
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 48h
  secretStoreRef:
    name: ssm
    kind: ClusterSecretStore
  target:
    name: cloudflare-external-secret
  data:
    - secretKey: api_token
      remoteRef:
        key: /homelab/prod/cloudflare_api_key
    - secretKey: account_id
      remoteRef:
        key: /homelab/prod/cloudflare_account_id
    - secretKey: tunnel_name
      remoteRef:
        key: /homelab/prod/cloudflare_tunnel_name